### ISSUE TITLE
Question - undocumented NetKVM parameters / effects

### ISSUE THREAD

**Issue by Jozodezokokotar** [YanVugenfirer/kvm-guest-drivers-windows#68]
Hello guys,

I've been googling a lot to find out how the following parameters affect latency.
Unfortunately, there is very little or no description of what they do and how they affect latency.

My goal is get low latency setup at the expense of higher CPU usage and lower throughput.
The question is, will the following values help me or not?

MergeableBuf = "Init.UseMergedBuffers" = True
Indirect = "Init.IndirectTx"  = True
RxCapacity = "Init.MaxRxBuffers" = 1024 (default 256)
NumberOfHandledRXPackersInDPC = "TestOnly.RXThrottle" = 100  (default 1000)

Thank you very much

**Comment by YanVugenfirer** [comment]
Hi,

Init.UseMergedBuffers - It can disable mergeable buffer feature of virtio.
Keeping it "ON" makes things more efficient as data and virtio header will
use only one ring descriptor on RX instead of two. I think this parameter
should be removed as it make no sense to keep it and the feature is
negotiable between host and guest (meaning if host doesn't support it,
driver will automatically adapt anyway),

Indirect - enables usage of indirect buffers for virtio. It enables to pass
in one descriptor list of descriptors. This is a must feature for different
offload options. Once again, better remove it from UI.


RxCapacity - Initial RX buffer amount preallocated by the drivers.
Enlarging this number can make things better (on expense of memory), but
you need to make sure that host side also using larger rings. I am not sure
if today this values has actual meaning, as we will always try to allocated
according to the host. Need to check the code.

NumberOfHandledRXPackersInDPC  - amount of packets that will be process in
one DPC (SW interrupt). Making this number small could hurt throughput.
Enlarging it too much could starve the core that is used for RX processing
for other usage. So playing with this value might help you.


Best regards,
Yan.




On Wed, Jun 1, 2016 at 10:45 AM, Jozodezokokotar <notifications@github.com>
wrote:

> Hello guys,
>
> I've been googling a lot to find out how the following parameters affect
> latency.
> Unfortunately, there is very little or no description of what they do and
> how they affect latency.
>
> My goal is get low latency setup at the expense of higher CPU usage and
> lower throughput.
> The question is, will the following values help me or not?
>
> MergeableBuf = "Init.UseMergedBuffers" = True
> Indirect = "Init.IndirectTx" = True
> RxCapacity = "Init.MaxRxBuffers" = 1024 (default 256)
> NumberOfHandledRXPackersInDPC = "TestOnly.RXThrottle" = 100 (default 1000)
>
> Thank you very much
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/68>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABDkWF5ATeQZwMjwhOWJKd1MVCtTabtCks5qHTifgaJpZM4IrRa_>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by Jozodezokokotar** [comment]
Once again, thank you very much for your help.
I hope this thread will be crawled by google robots so that it will help other 'oblivious googlers' like me.

**Comment by YanVugenfirer** [comment]
There is also official documentation -
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Virtualization_Host_Configuration_and_Guest_Installation_Guide/netkvm-parameters.html


On Wed, Jun 1, 2016 at 1:32 PM, Jozodezokokotar <notifications@github.com>
wrote:

> Once again, thank you very much for your help.
> I hope this thread will be crawled by google robots so that it will help
> other 'oblivious googlers' like me.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/68#issuecomment-222954708>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABDkWDmhikRDKmkQ1vyw-hDbBkb8VWJlks5qHV-zgaJpZM4IrRa_>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com
